#!/bin/bash
set -eu
this_dir=$(readlink -e "${0%%/*}")
jenkins_home="$this_dir/home"
mkdir -p "$jenkins_home" 2>/dev/null || true
sudo docker run -p 8080:8080 -p 50000:50000 \
    -v "$jenkins_home":/var/jenkins_home \
    -v "$HOME"/.ssh:/var/jenkins_home/.ssh \
    docker-jenkins-slave
